### ISSUE TITLE
RNIapModule.buyItemByType got 6 arguments, expected 7

### ISSUE THREAD

**Issue by jamesalester** [dooboolab/react-native-iap#1131] opened 2020-09-25 18:41 UTC
### Version of react-native-iap
4.6.2

### Version of react-native
0.62.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
It should perform a purchase and then call the purchaseUpdatedListener but it never gets that far.

### Actual behavior
It comes up with an error saying `RNIapModule.buyItemByType got 6 arguments, expected 7`

### Tested environment (Emulator? Real Device?)
Tested on an Android emulator

### Steps to reproduce the behavior
As soon as `await RNIap.requestPurchase(sku, false);` is called.

![image](https://user-images.githubusercontent.com/19751644/94304167-f62b4780-ff66-11ea-8d9b-2eb7e9a24b75.png)

I noticed someone else had a similar issue and fixed it by removing node_modules and reinstalling but I've done that numerous times to no success.

**Comment by nochkin** [comment] 2020-09-25 22:34
Funny enough, I just had the same issue and have a fix for it.
I just created a PR to address it: https://github.com/dooboolab/react-native-iap/pull/1132

**Comment by hyochan** [comment] 2020-09-26 06:49
Fixed in `4.6.3`

**Closed by hyochan** 2020-09-26 06:49 UTC

**Comment by jamesalester** [comment] 2020-09-26 13:20
Awesome! Can confirm it's working now, thanks!

**Comment by bcbcbcbcbcl** [comment] 2020-10-13 15:07
@hyochan I'm getting this error in v 4.6.3, any idea what could be the causes?
<img src="https://user-images.githubusercontent.com/39854319/95878366-b8705080-0da7-11eb-9857-0aeddcb982d2.jpg" width="300">

**Comment by nochkin** [comment] 2020-10-13 17:40
@bcbcbcbcbcl 
It does not look to be the same issue. Anyway, I could not replicate the issue using the latest release.
Try to remove "node_modules" directory, re-fetch your dependencies and re-build clean.
