### ISSUE TITLE
Attempt to invoke interface method 'IInAppBillingService.getPurchases()' on a null object reference

### ISSUE THREAD

**Issue by eminsr** [dooboolab/react-native-iap#310] opened 2018-11-06 13:50 UTC
### Version of react-native-iap
"react-native-iap": "^2.3.17"
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
it should check if `mService` is null before calling `getPurchases()`
### Actual behavior
It doesn't check if `mService` is null and throws this error
`Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference`
### Tested environment (Emulator? Real Device?)
Real Device Android 6.0
### Steps to reproduce the behavior
Just call RNIap.getAvailablePurchases() after initConnection(),
```
const result = await RNIap.initConnection();
const purchases = await RNIap.getAvailablePurchases();
```
I temporarily fix it by setting a timeout for `getAvailablePurchases()`

**Comment by dooboolab** [comment] 2018-11-06 15:59
Can you show us in which line of code in `Android` it occurs? If it is wrapped with `ensure connection` it should be fine because it is checking whether `mService` is null. Where do you think the problem is occurring?

**Comment by eminsr** [comment] 2018-11-06 16:13
I think after `mBillingClient.startConnection()` called there is a time gap until `ServiceConnection` is actually connected. Until then `mService` is `null`. If I don't wait a few seconds before calling the `RNIap.getAvailablePurchases()` function, app crashes.

**Comment by eminsr** [comment] 2018-11-08 15:28
I spoke too soon it still causing a crash.

I think there is a time gap between `onBillingSetupFinished` and `onServiceConnected`. `initConnection()` resolves on `onBillingSetupFinished` but until the service is connected `mService` is null.

To fix it in `RNIapModule` I simply `catch` the `NullPointerException` and reject the promise than when `getAvailablePurchases()` is rejected, in the catch I started another `getAvailablePurchases()` request.

If we can find a solution to resolve `initConnection()` after the `mService` is not null that would be great.  But I can't think any way that doesn't involve a listener for `mService`.

**Comment by dooboolab** [comment] 2018-11-08 17:15
@eminsr Could you give a `PR` on what you've tried first? It might be helpful.

**Comment by dooboolab** [comment] 2018-11-09 04:08
Just merged your `PR` lets see what we can do. Also @LinusU can you give some help with this issue? I remember you've updated some codes here.

**Comment by LinusU** [comment] 2018-11-09 10:34
@eminsr could we modify `ensureConnection` to wait for `mService` as well? That should work, right 🤔

**Comment by eminsr** [comment] 2018-11-09 10:38
@LinusU yea that should fix the issue.

**Comment by eminsr** [comment] 2018-11-13 09:53
Maybe we can add a while loop to `initConnection()` but this doesn't seem like the right way to do it.
```
  @ReactMethod
  public void initConnection(final Promise promise) {
    ensureConnection(promise, new Runnable() {
      @Override
      public void run() {
        while(mService == null){
          Thread.sleep(250);
        }
        promise.resolve(true);
      }
    });
  }
```

**Comment by hyochan** [comment] 2018-12-27 09:16
I will close this since this is related #315

**Closed by hyochan** 2018-12-27 09:16 UTC
Labels: android, help wanted
