### ISSUE TITLE
Execution failed for task ':react-native-iap:compilePlayReleaseKotlin'.

### ISSUE THREAD

**Issue by illegal-instruction-co** [dooboolab/react-native-iap#1541] opened 2021-10-13 16:38 UTC
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
^8.0.0-rc.2
### Version of react-native
 ^0.65.1
### Platforms you faced the error (IOS or Android or both?)
android

**Comment by davidascholer** [comment] 2021-11-23 08:19
Same issue. Thanks for writing InAppPurchase hyochan, though I can't sign my application due to this same issue.

**Comment by davidascholer** [comment] 2021-11-23 09:50
I found my issue. Looking at the stacktrace, my project was using Kotlin 1.4.10 which is incompatible with the Kotlin 1.5 react-native-iap was using. Instead of trying to upgrade my kotlin.jar file or reverting to an older version of react-native-iap, I recreated the app. It works now.

**Comment by pierroo** [comment] 2021-12-23 12:00
I am actually facing this issue as well, I added what you suggested @hyochan unfortunately the issue remains the same:

```
Task :react-native-iap:compilePlayDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
```

It seems that the issue comes from using the "react-native-pager-view" that uses kotlin v1.4.10 when iap uses 1.5.0, but I am clueless on how to solve this depedency issue. :/

**Comment by millisecond** [comment] 2021-12-29 17:58
@pierroo I struggled with this for a while too and wound up downgrading from react-native-iap@next to the latest release version (7.5.3) and that resolved it.

**Comment by pierroo** [comment] 2021-12-29 18:16
> @pierroo I struggled with this for a while too and wound up downgrading from react-native-iap@next to the latest release version (7.5.3) and that resolved it.

Life saver: it fixed the issue right away; and I'm not sure I need anything from the @next version.
Should have thought about it, thank you so much @millisecond ! :)

**Comment by andresesfm** [comment] 2022-01-24 23:59
This has been fixed in the latest RC. now you can specify `kotlinVersion` on the `rootProject` in Gradle

**Closed by andresesfm** 2022-01-24 23:59 UTC
Labels: 🙏 help wanted, 🤖 android, ⓐ amazon, 📦 next

**Comment by fdobre** [comment] 2022-09-26 16:07
I can confirm setting `kotlinVersion` in rootProject in Gradle works with `react-native-iap 8.6.7` and ` RN 0.66.4`

**Comment by saumya66** [comment] 2024-07-16 12:41
a question - changing to what kotlinVersion worked exactly in build.gradle?

**Comment by Abdelalim-dev** [comment] 2024-07-26 06:37
@saumya66 using version 1.9.0 worked for me.

> react-native-iap: 12.5.1
> react-native: 0.66.5
