### ISSUE TITLE
getSubscriptions and getProducts numerous issues

### ISSUE THREAD

**Issue by kevinEsherick** [dooboolab/react-native-iap#272] opened 2018-09-25 23:16 UTC
### Version of react-native-iap
2.2.2
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Return only products/subscriptions for listed SKUs and return them in order. 
### Actual behavior
getProducts returns all IAPs, regardless of whether they are included in the list of SKUs. The documentation acknowledges that prior to 11.2 it will return subscriptions if they are included in the list of SKUs, but makes it seem as if it will only return those included in the list passed to this method. Instead it returns all IAPs. Meanwhile, getSubscriptions returns the subscriptions properly based on SKU list provided as argument to the method, but returns them in an indeterminate order. It usually returns them in the order provided, but sometimes jumbles it up, meaning that you can't tie anything in your code to an index of the array of subscription products returned by getSubscriptions—sometimes it might swap the indexes and return the wrong product. For now I'm using a for loop to sort the products by title and assign them to variables, but this is unintuitive and should at least be noted in the docs. 
### Tested environment (Emulator? Real Device?)
Real device, iPhone 6
### Steps to reproduce the behavior
Here's a quick, incomplete example:
```
const monthlySKU = 'monthly'
const yearlySKU = 'yearly'
const subscriptions = getSubscriptions([monthly, yearly])
const monthlySubscription = subscriptions[0]
const yearlySubscription = subscriptions[1]
```
Sometimes these will get flipped (monthlySubscription is assigned to the product associated with the 'yearly' SKU, and vice versa). Maybe 1 out of every 5 times or so for me right now.

**Comment by JJMoon** [comment] 2018-09-27 08:17
This is side effect of prior resolving another prior issue.
You have to make a one SKU for subscription, one for products.
And the return array will include the both products.
We decided to keep the results from Apple, and over write the products when receiving new lists.

The action you mentioned above is as expected.

**Comment by kevinEsherick** [comment] 2018-09-27 17:16
Are you saying that it is intended behavior for getSubscriptions to return a list of subscriptions in an order different from the order of the SKUs you passed to it? Are you also saying that it's intended for getProducts to return an array of all products and all subscriptions, even those whose SKUs weren't passed as arguments to the function? For example, I could have 3 products/subscriptions: 'a', 'b', and 'c'. If I call getProducts(['a', 'b']), it will return the products associated with 'a', 'b', and 'c', instead of just 'a' and 'b' as I would expect. Are you saying that this is intended for some reason? Or are you just saying it is a known side effect right now that is expected until a workaround is devised?

**Comment by JJMoon** [comment] 2018-09-30 01:58
Q : Are you saying that it is intended behavior for getSubscriptions to return a list of subscriptions in an order different from the order of the SKUs you passed to it? 
A : Yes.
Q : Are you also saying that it's intended for getProducts to return an array of all products and all subscriptions, even those whose SKUs weren't passed as arguments to the function? 
A : Yes. Because, there is only one array of valid products in our module.
So, you need to check the target items in the array. And getting all the valid products once at the first is best practice.

**Comment by dooboolab** [comment] 2018-10-04 07:05
@kevinEsherick Do you think #278 can solve your problem?

**Closed** 2018-10-28 11:02 UTC
Labels: help wanted, iOS
