### ISSUE TITLE
IOS Build Crash

### ISSUE THREAD

**Issue by BLOCKMATERIAL** [dooboolab/react-native-iap#1758] opened 2022-07-25 17:30 UTC
### Version of react-native-iap
8.3.0

### Version of react-native
0.64.2

### Platforms you faced the error (IOS or Android or both?)
IOS Platfrom

### Description
An error occurs when building the IOS version .

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
1.Install package npm
2.pod install
3.Build app

![image](https://user-images.githubusercontent.com/46076319/180838629-dfd02fc0-e578-4f1b-9346-17939880483c.png)

**Comment by sercaneryaz** [comment] 2022-07-25 18:10
have you ever get this error ever?
![Ekran Resmi 2022-07-25 21 10 05](https://user-images.githubusercontent.com/40642548/180845287-e5e14c94-ec21-4ac4-96da-dde766bc17ac.png)

**Comment by sercaneryaz** [comment] 2022-07-25 18:46
@BLOCKMATERIAL downgrading to 8.1.1 is worked for me on same bug

**Comment by andresesfm** [comment] 2022-07-25 19:51
Duplicate of https://github.com/dooboolab/react-native-iap/issues/1757

**Closed by andresesfm** 2022-07-25 19:51 UTC
Labels: 📱 iOS
