### ISSUE TITLE
buySubscription ignoring user feedback

### ISSUE THREAD

**Issue by marcosmartinez7** [dooboolab/react-native-iap#279] opened 2018-10-05 23:02 UTC
### Version of react-native-iap

2.3.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior

let sub = await RNIApp.buySubscription("some");

should wait for the user to press buy on the modal of in app payments

### Actual behavior

i cant check if the user accepted the subscription, because when doing:

let sub = await RNIApp.buySubscription("some");
if(sub){
   do some things..
}

the if(sub) block executes inmediatly after the popup opens, but the user still not accept the subscription

### Tested environment (Emulator? Real Device?)

Real device

Any ideas?

There  are other methods like getAvailablePurchases that also returns a promise and works fine

The problem is that buySubscription should return the callback of the user input and it isnt

**Comment by marcosmartinez7** [comment] 2018-10-05 23:12
Literally didnt touch anything, and after some uninstall/install it works, any ideas if this must be related with the playstore working wrong? 

Its the only logical explanation that i can imagine ..

**Comment by dooboolab** [comment] 2018-10-07 08:18
@marcosmartinez7 Sorry for the breaking could you try `2.3.1`?

**Comment by marcosmartinez7** [comment] 2018-10-08 21:14
Hi, thanks! 

I dont have time right now but i will

**Comment by dooboolab** [comment] 2018-10-09 12:17
@marcosmartinez7 Thanks please come back.

**Comment by Gaia-Nutrition** [comment] 2018-10-10 09:43
@dooboolab Issue is present on iOS too. Tried both `2.3.1` as well as `2.3.2`

**Comment by dooboolab** [comment] 2018-10-10 18:35
I think it is fixed in `2.3.3`. Please reopen when this is still occurring.

**Comment by Gaia-Nutrition** [comment] 2018-10-10 21:04
@dooboolab I'm sorry, just installed and relinked `2.3.5`. `await RNIap.buySubscription(iapProductId)` still immediately returns `undefined` on iOS

**Comment by Gaia-Nutrition** [comment] 2018-10-10 21:31
@dooboolab I tried linking and unlinking. Whenever I switch back to `2.2.2` it starts working again. But I'll check again tomorrow. Maybe try to manually install the native component

**Comment by Gaia-Nutrition** [comment] 2018-10-11 06:47
@dooboolab Ok, I now manually linked the new `2.3.6` version. Still getting `undefined`. I'd love to help solve this issue. Let me know what I can do to help!

**Comment by dooboolab** [comment] 2018-10-11 09:58
Can somebody confirm this? This shouldn't happen.

**Comment by freakyfriday** [comment] 2018-10-13 04:20
@dooboolab I can confirm that on iOS version 2.3.6 doesn't execute the promises but version 2.2.2 does (using an iPhone 5 device, React Native 0.56)

**Comment by JJMoon** [comment] 2018-10-15 07:32
I guess this is same issue with this.
https://github.com/dooboolab/react-native-iap/issues/201

Would you check this?

**Comment by medlJeremy** [comment] 2018-10-15 21:57
I am also experiencing this issue on 2.3.7. When i try to use `await` the next line is called right away instead of waiting for the promise, and when i use `RNIap.buySubscription(subId).then(purchase => {})` it crashes with error cannot read property then of undefined

**Comment by dooboolab** [comment] 2018-10-15 23:11
We're currently working on this. Also, anyone who is facing this, did you call `getSubscriptions` before actually calling `buySubscription`?

**Comment by JJMoon** [comment] 2018-10-16 06:56
I just tested purchase in RNExample app. I purchased subscription with buyProductWithoutFinishTransaction() method.

**Comment by dooboolab** [comment] 2018-10-17 00:17
@Gaia-Nutrition Can you try `2.3.8`? Also, what did you call `getSubscriptions` before `buySubscription`?

**Comment by JJMoon** [comment] 2018-10-19 06:44
I tested buySubscription in iOS device in sandbox mode.
It managed to success, but it shows some error message.
And Auto renewable subscription doesn't issue receipt.
I suggest to use buyProductWithoutFinishTransaction and finishTransaction instead of buySubscription.
Currently I have no device for test, I will track this issue later.

**Comment by dooboolab** [comment] 2018-10-19 15:00
Feels like this is only issue in `iOS` currently. Am I right?

**Comment by mfentross** [comment] 2018-10-19 15:17
@dooboolab No, also occuring on Android. The function returns undefined even before the first line in buyItemByType is called.

**Comment by mfentross** [comment] 2018-10-19 15:28
@dooboolab The problem is caused in the index.js:105. You should change the lines to something like 

`
export const buySubscription = (sku, oldSku, prorationMode) => Platform.select({
    ios: () => RNIapIos.buyProduct(sku),
    android: () =>  RNIapModule.buyItemByType(ANDROID_ITEM_TYPE_SUBSCRIPTION, sku, oldSku, -1),
  })();
`
(I know this ignores prorationMode)

However after successfully subscribing there is an issue:

`
E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.dooboolab.RNIap.RNIapModule$11.onPurchasesUpdated(RNIapModule.java:427)
        at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
        at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
        at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
        at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`

**Comment by dooboolab** [comment] 2018-10-20 02:11
@mfentross Which version of `react-native-iap` are you at? There is empty line in `RNIapModule.java:427`.

**Comment by mfentross** [comment] 2018-10-20 07:55
My fault: I edited a few lines. But the fix for the main problem is to edit the buySubscription function to

`
export const buySubscription = (sku, oldSku, prorationMode) =>
    Platform.select({
        ios: () => RNIapIos.buyProduct(sku),
        android: () => {
            if (!prorationMode) prorationMode = -1;
            return RNIapModule.buyItemByType(ANDROID_ITEM_TYPE_SUBSCRIPTION, sku, oldSku, prorationMode);
        },
    })();

`

There were some unnecessary brackets.

**Comment by mfentross** [comment] 2018-10-20 16:53
@dooboolab Thanks, it works now 👍

**Comment by dooboolab** [comment] 2018-10-23 14:56
@JJMoon He says if wrap method with `async` and `await`, it works. However, I am not quite sure how this could be possible. Wrapping with `async` and `await` is redundant in return value isn't it?

**Comment by dooboolab** [comment] 2018-10-24 10:17
Please reopen when this is still occurring. Thank you for all helps.

**Closed by dooboolab** 2018-10-24 10:17 UTC
Labels: iOS, regression
