### ISSUE TITLE
"Cannot connect to iTunes Store" E_UNKNOWN - Auto-renew subs (in Production)

### ISSUE THREAD

**Issue by diegogurpegui** [dooboolab/react-native-iap#878] opened 2019-12-17 21:42 UTC
I know this error has been reported before, but I don't think with these conditions: **Real device + Production + Auto-renew subscription**.

### Version of react-native-iap
4.3.4 (previously on 3.5.6 too)

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Make a purchase of an auto-renewable subscriptions without issue.

### Actual behavior
The system is throwing the error "Cannot connect to iTunes Store" (code: E_UNKNOWN).
The purchase is registered in the App Store, but the react native app gets the error and cannot continue.

### Tested environment (Emulator? Real Device?)
Real Device. In PRODUCTION (not sandbox).

### Steps to reproduce the behavior
Purchase a subscription.
`await RNIap.requestSubscription(sku);`

It seems to be happening on second or more subscriptions. The first ever subscription with the app for a user sometimes works. But after that it keeps failing.

The error is fired by the `await RNIap.requestSubscription(sku);`, and also in the `purchaseErrorListener`

**Comment by diegogurpegui** [comment] 2020-01-02 13:03
Still getting this error on version 4.3.4.
I'm editing the original post from version 3.5.6 to 4.3.4

**Comment by hyochan** [comment] 2020-01-05 09:33
Have you called `finishTransaction`?

**Comment by diegogurpegui** [comment] 2020-01-06 12:44
> Have you called `finishTransaction`?

Yes I did. However, the past couple of days we re-build the app and tried to make sure `react-native-iap` was cleared and rebuilt (because of the version upgrade).
As of now the problem is no longer there. So, if fixed it would be because of the version upgrade of this module.
I'll keep this issue updated.


> Also please provide the error messages.

If the problem arises again I'll post the exact error. But it was the one in the title of this issue.

**Comment by hyochan** [comment] 2020-01-06 13:08
@diegogurpegui Thanks for coming back! I'll close this for now and please feel free to reopen when the problem arises.

**Closed by hyochan** 2020-01-06 13:08 UTC
Labels: help wanted, iOS, waiting for customer response

**Comment by jessicazu** [comment] 2021-01-19 02:31
We are using 5.1.3. In a production environment, the probability is about 3% that code: E_UNKNOWN will be returned and RNIap.PurchaseError will respond.
We are reproducing this with two things: subscriptions and consumable items.
There are many patterns that are not actually charged, but there are also reports of subscriptions actually being charged.
I have already reported this to Apple's TSI, but If anyone has reproduced it or has any knowledge about it, I would appreciate it if you could let me know. We believe that this library is probably not the cause of the problem.

Error messages in Japanese
```
{
  code: E_UNKNOWN, 
  debugMessage: 操作を完了できませんでした。（SKErrorDomainエラー0）, 
  message: 操作を完了できませんでした。（SKErrorDomainエラー0）, 
}
```

```
{
  code: E_UNKNOWN, 
  debugMessage: 不明なエラーが起きました, 
  message: 不明なエラーが起きました, 
}
```
