### ISSUE TITLE
Reconnecting billingClient is not working

### ISSUE THREAD

**Issue by Mkolakoglu** [dooboolab/react-native-iap#1733] opened 2022-06-23 14:49 UTC
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. Please report issue if there is a bug.

### Version of react-native-iap
8.1.3
### Version of react-native
0.68.1
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
When I call `initConnection` -> `endConnection` -> `initConnection` (again), the iap service can not be used. I am thinking that it will not reconnect when the connection is lost because of the long lived connections on Android.
### Actual behavior
The iap service should be able to be used after calling `initConnection` -> `endConnection` -> `initConnection` (again)
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Call `initConnection` -> `endConnection` -> `initConnection` and then try to purchase subscription

**Comment by andresesfm** [comment] 2022-06-23 22:40
@Mkolakoglu can you please describe if you get an error? are you manually ending the connection every time? As you can see here: https://github.com/android/play-billing-samples/blob/master/TrivialDriveJava/app/src/main/java/com/sample/android/trivialdrivesample/billing/BillingDataSource.java#L206 They don't need to set the client to null, they simply retry to connect.  

@ifsnow you mentioned you are experiencing the same even after my changes? If so, are you saying that @Mkolakoglu 's PR fixes it for you?

Note that I have no problem with setting the billing client to null, I just think it's better to follow the official example from Google but if that doesn't work we can modify it

**Comment by ifsnow** [comment] 2022-06-23 23:37
@Mkolakoglu This issue occurs in the latest version. Rolling back to the previous version fixed it right away.

You can easily reproduce it with the steps below. It seems to be the same in the emulator.

- Start the app
- Using react-native-iap
- Close the app with the back button
- Restart the app
- Connection error when using react-native-iap

**Comment by andresesfm** [comment] 2022-06-23 23:52
@ifsnow Do you mean rolling back from `8.1.3` back to `8.1.2` fixed the issue?

**Comment by andresesfm** [comment] 2022-06-23 23:55
Can you kindly post here any error messages/logs you are seeing? It might be easier to rollback that small change than it is to convert to null objects

**Comment by Mkolakoglu** [comment] 2022-06-24 08:52
Here is the error log: 

<img width="1039" alt="Screen Shot 2022-06-24 at 10 47 20" src="https://user-images.githubusercontent.com/16003411/175499452-5256063e-526a-4c0c-b69c-79db5c1b606e.png">

The main fix I applied was adding `billingClient = BillingClient.newBuilder(reactContext).enablePendingPurchases().setListener(this).build()` into `initConnection()`. The rest can be reverted if you are not fine with them

**Comment by hyochan** [comment] 2022-06-26 10:18
Looks like this is resolved in `8.2.0`. Please come back if this is not resolved. Thanks again @Mkolakoglu 🥇

**Closed by hyochan** 2022-06-26 10:18 UTC
Labels: 🤖 android
