### ISSUE TITLE
[Android] [3.0.0-rc.10] requestSubscription() error DF-DFERH-01

### ISSUE THREAD

**Issue by m-ochyra** [dooboolab/react-native-iap#530] opened 2019-06-17 09:21 UTC
### Version of react-native-iap
3.0.0-rc.10

### Version of react-native
0.59.9

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Buy subscription

### Actual behavior
Play Store error: DF-DFERH-01

### Tested environment (Emulator? Real Device?)
Nexus 5X Android 8.1.0
Emulator x86 Android 9

### Steps to reproduce the behavior
- update react-native-iap from version 2.5.5 to 3.0.0-rc.10
- change RNIap.buySubscription(productId) (works fine on version 2.5.5) to RNIap.requestSubscription(productId)

**Comment by sameerjain** [comment] 2019-06-17 09:59
I was having similar issue. Doc says you should call "requestSubscription" which was failing for me so just give requestPurchase a try with subscription SKU and it worked like a treat. Hope this help. Thanks

**Comment by hyochan** [comment] 2019-06-17 10:10
@sameerjain This isn’t a good idea since billingFlow will distinguish the sub or inapp.

DF-DFERH-01 error is matter of cache in android device. Please figure this out by [solution](https://m.youtube.com/watch?v=yObPPF6tCXs) and try again.

**Comment by sameerjain** [comment] 2019-06-17 10:35
@hyochan Well, In that case I think there is a bug in the library itself. I tried all the solutions. I am working on this from last 3 days, well almost. At the end this is the only thing worked. I am really not sure how it works internally but if I look at the logcat it seems the flow is correct and I get correct json. Google billing also show this is a subscription with all correct info like billing period, trial period with localized price and warning that it will be recurring. As soon I use requestSubscription it show me that error again. I am attaching images for both api method

requestSubscription 
![image](https://user-images.githubusercontent.com/2406252/59598087-04aa7280-9119-11e9-97e3-8f7f98522ded.png)

requestPurchase
![image](https://user-images.githubusercontent.com/2406252/59598349-9a460200-9119-11e9-882b-20f9351e2cb0.png)

Hope this help in.
Thanks

**Comment by hyochan** [comment] 2019-06-17 14:58
I'm concerned that this may happen due to the migration of `billing` library in `android` from `1.x` ==> `2.0.1`.

**Comment by hyochan** [comment] 2019-06-17 17:41
Another question have you guys fetched product by `getSubscriptions(skus)` instead `getProducts`?

**Comment by hyochan** [comment] 2019-06-17 18:09
#526 has a similar issue and @rborn has resolved this. @rborn I hope you can share your experience in this thread too.

**Comment by rborn** [comment] 2019-06-17 18:10
@hyochan @sameerjain I didn't solve the DF-DFERH-01 error sadly  😔

I just solved the `getSubscriptions` part...

**Comment by rborn** [comment] 2019-06-17 18:19
@hyochan I think  @sameerjain is right, it works with `requestPurchase` and yes  I used `getSubscriptions(skus)`

**Comment by hyochan** [comment] 2019-06-17 18:21
Ok. Let me go over this issue on the weekend.

**Comment by sameerjain** [comment] 2019-06-17 18:31
For me both work fine and responses I am getting from both are correct. I get consumable in getProduct and subscription in getSubscription.

**Comment by rborn** [comment] 2019-06-17 19:01
@hyochan just one more thing - for me `await RNIap.getAvailablePurchases();` doesn't seem to return anything anymore, it just stays there. I was using it to validate the receipt.
I think I can workaround using `getPurchaseHistory` but it's missing some data from the receipt.

**Comment by anhdvz** [comment] 2019-06-18 03:42
I was having similar issue, after clear cache some caches of google play store now I can't getProducts or getSubscriptions, always return E_DEVELOPER_ERROR, is it relevant to Google?

**Comment by alexbazilev** [comment] 2019-06-18 11:39
Confirm the problem with 3.0.0.rc-10 on real device.

```
const itemSkus = [
          'android.test.purchased',
          'android.test.canceled',
          'android.test.item_unavailable'
        ]
await RNIap.getProducts(itemSkus)
RNIap.requestPurchase('android.test.purchased')
```

Works perfect (except getAvailablePurchases freeze).

While 

```
const itemSubs = [
          'android.test.purchased',
          'android.test.canceled',
          'android.test.item_unavailable'
        ]
await RNIap.getSubscriptions(itemSubs)
RNIap.requestSubscription('android.test.purchased')
```

returns Error DF-DFERH-01. However, getSubscriptions returns an array of correct subscriptions (including static test subscriptions and subscriptions really existing in Play Console). But none of them work when calling requestSubscription.

RNIap.getAvailablePurchases() doesn't return anything at all (not even empty array, just freezes) in both cases.

**Comment by hyochan** [comment] 2019-06-18 14:52
> @hyochan just one more thing - for me `await RNIap.getAvailablePurchases();` doesn't seem to return anything anymore, it just stays there. I was using it to validate the receipt.
> I think I can workaround using `getPurchaseHistory` but it's missing some data from the receipt.

Sorry for this. This is resolved in `3.0.0-rc.12`.

Let's focus on ` Error DF-DFERH-01` for now and I can't generate this in my `env`.

**Comment by hyochan** [comment] 2019-06-18 15:26
Please try `3.0.0-rc.13`. I think this will fix the issue. Feel free to reopen when it doesn't.

**Closed** 2019-06-18 15:26 UTC
Labels: android, help wanted

**Comment by rborn** [comment] 2019-06-18 15:45
@hyochan I will test in ~1h and report back ❤️

**Comment by rborn** [comment] 2019-06-18 17:39
@hyochan did you upgrade to android X  ? I have this now (just installed rc14)

```
Task :app:processDebugManifest FAILED
/Work/clients/current/emjoy/app/emjoy/android/app/src/debug/AndroidManifest.xml:22:18-91 Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-138 to override.


```

**Comment by rborn** [comment] 2019-06-18 18:16
Ok, updated to RNIap to rc 14, updated RN to 0.59.9, some other module and managed to get over the androidX issue.

However there are 2 problems, is not compiling (I'll make a PR for that ) and then the `DF-DFERH-01` is still there 😔

How can I get more logs for you? (I don't see anything in logcat)

**Comment by rborn** [comment] 2019-06-18 18:22
PR: https://github.com/dooboolab/react-native-iap/pull/535

**Comment by alexbazilev** [comment] 2019-06-18 20:05
I can confirm that `DF-DFERH-01` still exists in `3.0.0-rc.14` (with #535 update).

As I mentioned [above](https://github.com/dooboolab/react-native-iap/issues/530#issuecomment-503067226) - `requestPurchase` works correctly (after calling `getProducts` of course), but `requestSubscription` shows `DF-DFERH-01` error (after calling `getSubscriptions`)

**Comment by hyochan** [comment] 2019-06-19 01:27
Sorry guys 😥I was rushing late at night so I couldn't be better. I've just released `3.0.0-rc.16` and I think this must fix `DF-DFERH-01`.

**Comment by hyochan** [comment] 2019-06-19 03:24
Please confirm this since I'm planning to release `3.0.0` this week.

**Comment by rborn** [comment] 2019-06-19 07:23
@hyochan no need to be sorry, you are doing a great job ❤️
I ran a very quick test (is too early for me 😅) and it seems that `requestSubscription` works this time.
Let me please run a more extensive test and I'll report during the day
Thanks a lot 🤗

**Comment by alexbazilev** [comment] 2019-06-21 16:13
Great job @hyochan 
I finally got subscriptions ready to test
