### ISSUE TITLE
Errors with calling 'await RNIap.prepare();' for in app purchase in Android

### ISSUE THREAD

**Issue by nullarch** [dooboolab/react-native-iap#168] opened 2018-05-23 11:46 UTC
### Version of react-native-iap
the lastest version for now

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
calling 'await RNIap.prepare();' succesfully

### Actual behavior
I got an error message saying 'Illegal callback invocation from native module. This callback type only permits a single invocation from native code'

I have an error at the 347 line of RnlapModule.java when I use RNIapModule.java
'resolvePromisesForKey(PROMISE_PREPARE, null);' This is 347 line. I mean that when I try to implement it, I have an error.

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by dooboolab** [comment] 2018-05-23 15:00
@SlZeroth What is the version of your react-native? I'll watch this one tommorow. It's 12 PM in here, need to go to sleep :(

**Comment by dooboolab** [comment] 2018-05-24 17:38
@SlZeroth I've just tested in my environment and couldn't reproduce this one. Are you calling any native modules when trying to use `react-native-iap` method? Also, [this](https://github.com/Microsoft/react-native-code-push/issues/1259) might be helpful to you.

**Comment by pehagg** [comment] 2018-06-01 12:48
I'm having the same issue, appears to happen when we reset the app state (user signs in or out of Facebook and we need to re-sync all data). We essentially end up in a state where we call prepare for a second time. 

The error in the console is: `The callback prepare() exists in module RNIapModule, but only one callback may be registered to a function in a native module.`. 

Running RN 0.55.3 and RN IAP 1.0.5.

**Comment by pehagg** [comment] 2018-06-01 13:33
Workaround, track if prepare has been called at all and call endConnection before any subsequent calls.

**Comment by SlZeroth** [comment] 2018-06-01 16:33
@pehagg hmm .... I got same error The callback prepare() exists in module RNIapModule, but only one callback may be registered to a function in a native module..  on real device ,  where console did you saw  "Error: The service is disconnected (check your internet connection." error  ??

**Comment by SlZeroth** [comment] 2018-06-01 16:36
@pehagg  I tested react native iap module after upload alpha APP.

**Comment by SlZeroth** [comment] 2018-06-01 16:38
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Image,
  TouchableHighlight,
  ImageBackground,
  TouchableOpacity,
  FlatList,
  Alert,
  AsyncStorage
} from 'react-native';

import {
  WaveIndicator
} from 'react-native-indicators';

import * as RNIap from 'react-native-iap';

import { MAIN_COLOR } from '../utils/Color'
import { getUserInformation } from '../utils/http/Account'
import { applyPurchase } from '../utils/http/Payment'

const itemSkus = Platform.select({
  ios: [
    'crowncrown30'
  ],
  android: [
    'd30'
  ]
});

export default class PaymentScreen extends Component {
  static navigatorStyle = {
    tabBarHidden: true,
  };

  constructor(props) {
    super(props)

    this.state = {
      cashItems: [],
      cash: ''
    }

  }

  async getInapp() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }

  async _getUser() {
    userData = JSON.parse(await AsyncStorage.getItem('@conncting:user'))
    let responseJSON = await getUserInformation(userData.user.email)
    this.setState({ cash: responseJSON['cash'] })
  }

  async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
    
    this._getUser()
    this.getInapp()
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.myInfoContainer}>
          <View style={{ flexDirection: 'row', justifyContent: 'center', alignItems: 'center',}}>
            <Text style={styles.myDiamondText}>{this.state.cash}</Text>
            <Image style={styles.myDiamondImg} source={ require('../../assets/diamond.png') } />
          </View>
          <Text style={{ fontSize:20, color: 'gray' }} >보유 중인 다이아</Text>
        </View>

        <Text style={{ fontSize:18, marginLeft: 25, marginBottom: 5 }} >다이아 구매</Text>
        <FlatList 
          style={styles.flat}
          data={this.state.cashItems}
          keyExtractor={this._keyExtractor}
          renderItem={({item}) => 
            <TouchableOpacity style={{flex:1}} onPress={ ()=> this._buyProduct(item)} >
              <View style={styles.listItemRoot}>
                <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center'}}>
                  <Image style={styles.itemDiamond} source={ require('../../assets/diamond.png') } />
                  <Text style={styles.itemName}>{item.title}</Text>
                </View>
                <Text style={styles.itemPrice} >{item.localizedPrice}</Text>
              </View> 
            </TouchableOpacity> } />

      </View>
    )
  }

  async _buyProduct(item) {
    console.log(item)
    RNIap.buyProduct(item.productId).then(async (purchase) => {
      let responseJSON = await applyPurchase({ receipt_data : purchase.transactionReceipt })
      if(responseJSON['code'] == '1') {
        
      }
    }).catch(err => {
      alert(err.message);
    })
  }

  _keyExtractor = (item, index) => {
    console.log(index)
    return index + ""
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: '#ebebeb'
  },

  myInfoContainer: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
    marginBottom: 15,
  },

  myDiamondImg: {
    width: 42,
    height: 42,
    resizeMode: Image.resizeMode.contain
  },

  myDiamondText: {
    fontSize: 50,
    color: MAIN_COLOR,
    fontWeight: 'bold',
    marginRight: 20,
  },

  flat: {
    flex: 1
  },

  listItemRoot: {
    padding: 15,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center'
  },

  itemDiamond: {
    width: 25,
    height: 25,
    marginLeft: 15,
    marginRight: 30,
    resizeMode: Image.resizeMode.contain
  },
  
  itemName: {
    fontSize: 16
  },

  itemPrice: {
    fontSize: 16,
    marginRight: 15
  }
})

**Comment by SlZeroth** [comment] 2018-06-01 16:38
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Image,
  TouchableHighlight,
  ImageBackground,
  TouchableOpacity,
  FlatList,
  Alert,
  AsyncStorage
} from 'react-native';

import {
  WaveIndicator
} from 'react-native-indicators';

import * as RNIap from 'react-native-iap';

import { MAIN_COLOR } from '../utils/Color'
import { getUserInformation } from '../utils/http/Account'
import { applyPurchase } from '../utils/http/Payment'

const itemSkus = Platform.select({
  ios: [
    'crowncrown30'
  ],
  android: [
    'd30'
  ]
});

export default class PaymentScreen extends Component {
  static navigatorStyle = {
    tabBarHidden: true,
  };

  constructor(props) {
    super(props)

    this.state = {
      cashItems: [],
      cash: ''
    }

  }

  async getInapp() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }

  async _getUser() {
    userData = JSON.parse(await AsyncStorage.getItem('@conncting:user'))
    let responseJSON = await getUserInformation(userData.user.email)
    this.setState({ cash: responseJSON['cash'] })
  }

  async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
    
    this._getUser()
    this.getInapp()
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.myInfoContainer}>
          <View style={{ flexDirection: 'row', justifyContent: 'center', alignItems: 'center',}}>
            <Text style={styles.myDiamondText}>{this.state.cash}</Text>
            <Image style={styles.myDiamondImg} source={ require('../../assets/diamond.png') } />
          </View>
          <Text style={{ fontSize:20, color: 'gray' }} >보유 중인 다이아</Text>
        </View>

        <Text style={{ fontSize:18, marginLeft: 25, marginBottom: 5 }} >다이아 구매</Text>
        <FlatList 
          style={styles.flat}
          data={this.state.cashItems}
          keyExtractor={this._keyExtractor}
          renderItem={({item}) => 
            <TouchableOpacity style={{flex:1}} onPress={ ()=> this._buyProduct(item)} >
              <View style={styles.listItemRoot}>
                <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center'}}>
                  <Image style={styles.itemDiamond} source={ require('../../assets/diamond.png') } />
                  <Text style={styles.itemName}>{item.title}</Text>
                </View>
                <Text style={styles.itemPrice} >{item.localizedPrice}</Text>
              </View> 
            </TouchableOpacity> } />

      </View>
    )
  }

  async _buyProduct(item) {
    console.log(item)
    RNIap.buyProduct(item.productId).then(async (purchase) => {
      let responseJSON = await applyPurchase({ receipt_data : purchase.transactionReceipt })
      if(responseJSON['code'] == '1') {
        
      }
    }).catch(err => {
      alert(err.message);
    })
  }

  _keyExtractor = (item, index) => {
    console.log(index)
    return index + ""
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: '#ebebeb'
  },

  myInfoContainer: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
    marginBottom: 15,
  },

  myDiamondImg: {
    width: 42,
    height: 42,
    resizeMode: Image.resizeMode.contain
  },

  myDiamondText: {
    fontSize: 50,
    color: MAIN_COLOR,
    fontWeight: 'bold',
    marginRight: 20,
  },

  flat: {
    flex: 1
  },

  listItemRoot: {
    padding: 15,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center'
  },

  itemDiamond: {
    width: 25,
    height: 25,
    marginLeft: 15,
    marginRight: 30,
    resizeMode: Image.resizeMode.contain
  },
  
  itemName: {
    fontSize: 16
  },

  itemPrice: {
    fontSize: 16,
    marginRight: 15
  }
})`

**Comment by SlZeroth** [comment] 2018-06-01 16:38
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Image,
  TouchableHighlight,
  ImageBackground,
  TouchableOpacity,
  FlatList,
  Alert,
  AsyncStorage
} from 'react-native';

import {
  WaveIndicator
} from 'react-native-indicators';

import * as RNIap from 'react-native-iap';

import { MAIN_COLOR } from '../utils/Color'
import { getUserInformation } from '../utils/http/Account'
import { applyPurchase } from '../utils/http/Payment'

const itemSkus = Platform.select({
  ios: [
    'crowncrown30'
  ],
  android: [
    'd30'
  ]
});

export default class PaymentScreen extends Component {
  static navigatorStyle = {
    tabBarHidden: true,
  };

  constructor(props) {
    super(props)

    this.state = {
      cashItems: [],
      cash: ''
    }

  }

  async getInapp() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }

  async _getUser() {
    userData = JSON.parse(await AsyncStorage.getItem('@conncting:user'))
    let responseJSON = await getUserInformation(userData.user.email)
    this.setState({ cash: responseJSON['cash'] })
  }

  async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
    
    this._getUser()
    this.getInapp()
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.myInfoContainer}>
          <View style={{ flexDirection: 'row', justifyContent: 'center', alignItems: 'center',}}>
            <Text style={styles.myDiamondText}>{this.state.cash}</Text>
            <Image style={styles.myDiamondImg} source={ require('../../assets/diamond.png') } />
          </View>
          <Text style={{ fontSize:20, color: 'gray' }} >보유 중인 다이아</Text>
        </View>

        <Text style={{ fontSize:18, marginLeft: 25, marginBottom: 5 }} >다이아 구매</Text>
        <FlatList 
          style={styles.flat}
          data={this.state.cashItems}
          keyExtractor={this._keyExtractor}
          renderItem={({item}) => 
            <TouchableOpacity style={{flex:1}} onPress={ ()=> this._buyProduct(item)} >
              <View style={styles.listItemRoot}>
                <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center'}}>
                  <Image style={styles.itemDiamond} source={ require('../../assets/diamond.png') } />
                  <Text style={styles.itemName}>{item.title}</Text>
                </View>
                <Text style={styles.itemPrice} >{item.localizedPrice}</Text>
              </View> 
            </TouchableOpacity> } />

      </View>
    )
  }

  async _buyProduct(item) {
    console.log(item)
    RNIap.buyProduct(item.productId).then(async (purchase) => {
      let responseJSON = await applyPurchase({ receipt_data : purchase.transactionReceipt })
      if(responseJSON['code'] == '1') {
        
      }
    }).catch(err => {
      alert(err.message);
    })
  }

  _keyExtractor = (item, index) => {
    console.log(index)
    return index + ""
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: '#ebebeb'
  },

  myInfoContainer: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
    marginBottom: 15,
  },

  myDiamondImg: {
    width: 42,
    height: 42,
    resizeMode: Image.resizeMode.contain
  },

  myDiamondText: {
    fontSize: 50,
    color: MAIN_COLOR,
    fontWeight: 'bold',
    marginRight: 20,
  },

  flat: {
    flex: 1
  },

  listItemRoot: {
    padding: 15,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center'
  },

  itemDiamond: {
    width: 25,
    height: 25,
    marginLeft: 15,
    marginRight: 30,
    resizeMode: Image.resizeMode.contain
  },
  
  itemName: {
    fontSize: 16
  },

  itemPrice: {
    fontSize: 16,
    marginRight: 15
  }
})
`

**Comment by SlZeroth** [comment] 2018-06-01 16:39
`
export default class PaymentScreen extends Component {
  static navigatorStyle = {
    tabBarHidden: true,
  };

  constructor(props) {
    super(props)

    this.state = {
      cashItems: [],
      cash: ''
    }

  }

  async getInapp() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }

  async _getUser() {
    userData = JSON.parse(await AsyncStorage.getItem('@conncting:user'))
    let responseJSON = await getUserInformation(userData.user.email)
    this.setState({ cash: responseJSON['cash'] })
  }

  async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
    
    this._getUser()
    this.getInapp()
  }
}
`

**Comment by SlZeroth** [comment] 2018-06-01 16:39
export default class PaymentScreen extends Component {
  static navigatorStyle = {
    tabBarHidden: true,
  };

  constructor(props) {
    super(props)

    this.state = {
      cashItems: [],
      cash: ''
    }

  }

  async getInapp() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }

  async _getUser() {
    userData = JSON.parse(await AsyncStorage.getItem('@conncting:user'))
    let responseJSON = await getUserInformation(userData.user.email)
    this.setState({ cash: responseJSON['cash'] })
  }

  async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
    
    this._getUser()
    this.getInapp()
  }
}

**Comment by SlZeroth** [comment] 2018-06-01 16:40
`export default class PaymentScreen extends Component {
  static navigatorStyle = {
    tabBarHidden: true,
  };

  constructor(props) {
    super(props)

    this.state = {
      cashItems: [],
      cash: ''
    }

  }

  async getInapp() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log(products)
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
  }

  async _getUser() {
    userData = JSON.parse(await AsyncStorage.getItem('@conncting:user'))
    let responseJSON = await getUserInformation(userData.user.email)
    this.setState({ cash: responseJSON['cash'] })
  }

  async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      this.setState({ cashItems: products })
    } catch(err) {
      console.warn(err); // standardized err.code and err.message available
    }
    
    this._getUser()
    this.getInapp()
  }`

**Comment by dooboolab** [comment] 2018-06-07 11:51
@SlZeroth Are you still suffering? Have you read [this](https://github.com/Microsoft/react-native-code-push/issues/1259)?

**Comment by wasedaigo** [comment] 2018-06-08 10:53
I am getting the same error:
This is my dependencies:
```
"dependencies": {
    "bluebird": "^3.4.7",
    "lodash": "^4.17.4",
    "npm": "^6.1.0",
    "react": "^16.3.1",
    "react-native": "^0.55.3",
    "react-native-device-info": "^0.21.5",
    "react-native-exit-app": "^1.0.0",
    "react-native-firebase": "^4.2.0",
    "react-native-global-props": "^1.1.3",
    "react-native-iap": "^1.0.8",
    "react-native-sound": "^0.10.9",
    "react-native-store-view": "^3.1.1"
  }

**Comment by wasedaigo** [comment] 2018-06-08 11:06
ok, basically there is a pass that a promise can be called multiple times. In case I hit this line, the same promise will be invoked twice.
https://github.com/dooboolab/react-native-iap/blob/master/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L119

**Comment by dooboolab** [comment] 2018-06-08 15:13
@wasedaigo Sounds good if not calling `endConnection` was an issue. I felt like calling and finishing services in every purchase would result in some side effect so I left to other developers taste. I've just suggested to them starting service in billing component and ending it when `componentWillUnmount`. I'll be more specific in the readme sooner.

**Comment by wasedaigo** [comment] 2018-06-08 17:18
As long as it is clearly state in the docs calling endConnection is fine. I saw other libraries did open/close for this as well.

As long as we can avoid this magical error from appearing we should be able to close this issue

**Closed as completed** 2018-06-11 06:25 UTC
Labels: 🤖 android

**Comment by nkov** [comment] 2018-10-04 00:50
I am still having this issue and not much luck fixing it by calling `endConnection`. I have tried starting the service and calling `endConnection` on each billing action:

1. Verify purchases
```js
import * as RNIap from 'react-native-iap'

await RNIap.initConnection()
await RNIap.getProducts([SKU])
const products = await RNIap.getAvailablePurchases()
// some logic with the purchases
await RNIap.endConnection()
```

2. Make purchase
```js
await RNIap.initConnection()
await RNIap.getProducts([SKU])
await RNIap.buyProduct(SKU)
await RNIap.endConnection()
```

And I have also tried calling it on `componentWillUnmount` as described in the README.

In both cases, everything works, but _later on_ there is always a crash (ie. when the app is backgrounded), and the stack is the exact same as posted above. Using version 2.2.2 on Android.

**Comment by dooboolab** [comment] 2018-10-04 07:16
@nkov If you have some scenes which screen is holding `iap service` for long time, I prefer you to try more frequent lifecycle such as `onResume` and `onPause` in `android`. You may refer to use these lifecycle in [AppState](https://facebook.github.io/react-native/docs/appstate). Therefore, you may use `initConnection` when it is in `foreground` and `endConnection` when it isn't.
Could you try this and comeback?

**Comment by punksta** [comment] 2018-10-17 17:06
I am having the same issue too. I coded in similar way as @nkov  in `Make purchase`. It's still not clear what is proper way of calling initConnection and endConnection

**Comment by dooboolab** [comment] 2018-10-18 10:31
@punksta `initConnection` checks the availability for purchase in `ios` which is somewhat `trivial`. However, it is `critical` in `Android` because the `BillingService` in `Android` is not always running. To use the `billing` feature in `Android` you need to start `BillingService` which is what `initConnection` does.

**Comment by punksta** [comment] 2018-10-18 10:42
I understand it, it's clear. however calling initConnection second time after endConnection sometimes crashes the app. I meant that the flow is not very clear. 
`When you are done with the billing` is not very clear. 
Should I call  initConnection before each purchase and endConnection just after each? Or better to use AppState to close connection when app in background? Users can use billing few times per session

**Comment by pehagg** [comment] 2018-10-31 21:55
We're still experiencing issues with 2.3.12. The only way for me to get rid of the random errors we got because the connection was not open anymore or wasn't prepared, was to init the connection every time a purchase is being made and close it once the purchase is completed. However, this has now lead us to see these crashes in our logs: 

`Illegal callback invocation from native module. This callback type only permits a single invocation from native code`. 

Before making this change we initialised the connection every time the user arrived in the IAP screen, but as said, this wasn't enough, we got all kinds of random exceptions from RNIap. I'm running out of options and will need to start to look for another library if this cannot be sorted out.

**Comment by dooboolab** [comment] 2018-10-31 22:41
@pehagg You're missing `endConnection`. Please read the apis once more.

**Comment by pehagg** [comment] 2018-11-02 14:18
I call endConnection in the finally block of a try-catch-finally, where the init, purchase, and consumption is all done in the try block.

**Comment by dooboolab** [comment] 2018-11-03 03:57
show us the code so we can figure out

**Comment by pehagg** [comment] 2018-11-06 11:18
Here's the code. The only plausible explanation I can come up with is that there's an exception that is swallowed up by RNIap, which would explain that the finally block doesn't get called at all, or then the actual endConnection call fails.

```js
try {
    await RNIap.initConnection();
    const iap = <redacted> // find the IAP matching productIds
    if (iap) {
      const purchase = await RNIap.buyProduct(productId);
      await RNIap.consumePurchase(purchase.purchaseToken);
      <redacted>
    }
  } catch (error) {
     <redacted>
  } finally {
    try {
      await RNIap.endConnection();
    } catch (error) {
      <redacted>
    }
  }
```

**Comment by pehagg** [comment] 2018-11-07 06:52
Just noticed that the crash is coming from another part of the code, where we initialise the IAPs for the first time. The structure is the same, without the purchase and consumption. Here's a stack trace of such a case: 

```
com.facebook.react.bridge.CallbackImpl.invoke CallbackImpl.java:28
com.facebook.react.bridge.PromiseImpl.reject PromiseImpl.java:68
com.facebook.react.bridge.PromiseImpl.reject PromiseImpl.java:36
com.dooboolab.RNIap.RNIapModule.rejectPromiseWithBillingError RNIapModule.java:448
com.dooboolab.RNIap.RNIapModule.access$200 RNIapModule.java:44
com.dooboolab.RNIap.RNIapModule$3.onBillingSetupFinished RNIapModule.java:125
com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected BillingClientImpl.java:908
android.app.LoadedApk$ServiceDispatcher.doConnected LoadedApk.java:1818
android.app.LoadedApk$ServiceDispatcher$RunConnection.run LoadedApk.java:1847
android.os.Handler.handleCallback Handler.java:808
android.os.Handler.dispatchMessage Handler.java:101
android.os.Looper.loop Looper.java:166
android.app.ActivityThread.main ActivityThread.java:7425
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:245
com.android.internal.os.ZygoteInit.main ZygoteInit.java:921
```

In this case we got `E_SERVICE_ERROR` from `initConnection`. What happens if the `initConnection` call fails and you call `endConnection`, as this would be the case with this crash?
