### ISSUE TITLE
Android crashes in many devices after release

### ISSUE THREAD

**Issue by umutpiri** [dooboolab/react-native-iap#315] opened 2018-11-09 10:24 UTC
### Version of react-native-iap
 "react-native": "0.55.4"
"react-native-iap": "^2.3.2"
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Please help me, I need to fix this immediately. Because there are already +2k users
### Actual behavior
App crashes because of rniap in many devices. In play console, I saw this error causes the crash : 
java.lang.RuntimeException: 
1.  at com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:28)
2. at com.facebook.react.bridge.PromiseImpl.resolve (PromiseImpl.java:30)
3.  at com.dooboolab.RNIap.RNIapModule$4.run (RNIapModule.java:154)
4.  at com.dooboolab.RNIap.RNIapModule$3.onBillingSetupFinished (RNIapModule.java:123)
5.  at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected (BillingClientImpl.java:903)
6.  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1264)
7.  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1281)
8.  at android.os.Handler.handleCallback (Handler.java:815)
9.  at android.os.Handler.dispatchMessage (Handler.java:104)
10.  at android.os.Looper.loop (Looper.java:207)
11.  at android.app.ActivityThread.main (ActivityThread.java:5692)
12.  at java.lang.reflect.Method.invoke (Native Method)
13.  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:908)
14.  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769) 
### Tested environment (Emulator? Real Device?)
here is the report from play console : 
https://ibb.co/gDxZQA  
### Steps to reproduce the behavior
I don't know what to do, I used rniap like in example. 
in componentDidMount : 
try {
      const result = await RNIap.initConnection();
    } catch (err) {
      console.log(err);
    }
in componentWillUnmount: 
RNIap.endConnection();

**Comment by umutpiri** [comment] 2018-11-11 05:38
I can't. Because it was an immediate situation. So, I changed the iap package. Now there are no crashes in +3k users. But, thank you. I will try it in my next project.

**Comment by Ilario17** [comment] 2018-12-16 16:37
Hi, can you reopen this issue? I have the same problem and I'm using version 2.3.21

**Comment by hyochan** [comment] 2018-12-16 16:42
@LinusU Could you help us out here? Why would `callback.run()` crashes in release? Should we check whether `callback` is null in `ensureConnection`?

**Comment by LinusU** [comment] 2018-12-16 18:19
Hmmm, what does `RuntimeException` mean here, is there no more info? @hyochan why do you think that `callback` was `null`? 🤔

**Comment by hyochan** [comment] 2018-12-17 07:18
@LinusU If you don't have any idea about this one, I'd consider rolling this back to where we were at previously.

**Comment by LinusU** [comment] 2018-12-17 09:53
Okay, here is the problem:

https://github.com/facebook/react-native/blob/370bcffba748e895ad8afa825bfef40bff859c95/ReactAndroid/src/main/java/com/facebook/react/bridge/CallbackImpl.java#L27-L31

**Comment by hyochan** [comment] 2018-12-17 10:51
@LinusU Looks great because you are in a track! Could you give us a `PR` for this?

**Comment by Ilario17** [comment] 2018-12-18 08:49
Why is there a RuntimeException in that method?

```
if (!mInvoked) {
   mJSInstance.invokeCallback(mCallbackId, Arguments.fromJavaArgs(args));
   mInvoked = true;
}
```

is not something like this enough?

**Comment by LinusU** [comment] 2018-12-18 10:14
@hyochan sorry, didn't get time to look at this yesterday, hopefully I can take a look soon

@Ilario17 It's probably to flag that there is a logic error somewhere, to be fair, we shouldn't call that method multiple times

**Comment by hyochan** [comment] 2018-12-18 10:57
@LinusU So you mean `onBillingSetupFinished`, we should remove the `billingClientStateListener`. This should be an easy fix. Would someone try this one out to be part of us?

**Comment by Ilario17** [comment] 2018-12-19 10:36
I have no way to test, because on my devices it never crashes, but something like that could go?

`RNIapModule.java`
in `ensureConnection`

```
if (mBillingClient != null || isBillingClientReady) {
    callback.run();
    return
}
```

and on `onBillingSetupFinished`:

```
if (responseCode == BillingClient.BillingResponse.OK) {
      Log.d(TAG, "billing client ready");
      isBillingClientReady = true;
      callback.run();
   } else {
      rejectPromiseWithBillingError(promise, responseCode);
    }
```

```
public void onBillingServiceDisconnected() {
        Log.d(TAG, "billing client disconnected");
        isBillingClientReady = false;
      }
```

`isBillingClientReady` is a simple boolean, in this way the code should enter in`onBillingSetupFinished` just when start and when the service disconnected.

Maybe it's not the best way but how temporary solution could work? I have a lot of crashes and I'm looking for a quick solution

**Comment by LinusU** [comment] 2018-12-20 12:51
If you want a quick and dirty solution, I would add a local variable to that function, `didCallCallback = false`. Then guard the call to `callback.run()` behind `if (didCallCallback) { didCallCallback = true; callback.run() }`.

A cleaner solution would simply be to deregister the listener after the first call altogether...

**Comment by hyochan** [comment] 2018-12-26 02:48
I've just released `2.4.0-beta2` to make fixes on this. Please try.

**Comment by Ilario17** [comment] 2018-12-27 08:39
@hyochan I will try this new version

**Comment by hyochan** [comment] 2018-12-27 08:47
Please try 2.4.0-beta3 since beta2 had regression issue.

**Comment by Ilario17** [comment] 2018-12-28 10:45
@hyochan after the update the error is still there :(

**Comment by Ilario17** [comment] 2018-12-30 14:12
@hyochan why not just remove the listener, as @LinusU  said?

**Comment by hyochan** [comment] 2018-12-30 15:11
@Ilario17 I was curious if that's the right solution. Also, I feel `onBillingServiceDisconnected` should be notified.

**Comment by rom1k** [comment] 2019-01-01 17:59
I don't know if this is related but I'm getting this crash in 2.4.0-beta5. It's easy to reproduce in emulator:
I mount the component where IAP loads, unmount it and then mount it again, boom crash. Downgrading now to see if it helps.

```
Attempt to invoke virtual method 'void com.android.billingclient.api.BillingClient.querySkuDetailsAsync(com.android.billingclient.api.SkuDetailsParams, com.android.billingclient.api.SkuDetailsResponseListener)' on a null object reference
run
    RNIapModule.java:223
ensureConnection
    RNIapModule.java:113
getItemsByType
    RNIapModule.java:218
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764

```

**Comment by hyochan** [comment] 2019-01-02 06:11
@rom1k Well this would not work in android emulator. Please try in real device.

**Comment by Ilario17** [comment] 2019-01-02 10:41
@hyochan I notice that the version 2.4.0-beta3 has a 50% less crash, but still not enough

**Comment by csumrell** [comment] 2019-01-02 22:10
For 2.4.0-beta3 on Android I am getting error "Purchase failed with code: 0 (OK)" just from calling getProducts. beta 4 and 5 actually cause it to crash. I downgraded to 2.3.5 and it works fine, but I need the ios listener bug fixes in the 2.4.0-beta

```
        componentDidMount() {
		this.getProductDetails();
	}

	getProductDetails = async () => {
		try {
			await RNIap.initConnection();
			const details = await RNIap.getProducts(products);
			this.setState({
				title: details[0].title,
				description: details[0].description,
				price: details[0].localizedPrice,
				loading: false
			});
		} catch (err) {
			console.log(err.message)
		}
	};

**Comment by Ilario17** [comment] 2019-01-04 10:56
@hyochan @LinusU  with version 2.4.0-beta5 the error is still there.

**Comment by mitchellmcm27** [comment] 2019-01-06 21:44
I have some information relevant to this discussion.

On 2.4.0-beta5, I am getting the following error

`Attempt to invoke virtual method void com.android.billingclient.api.BillingClient.querySkuDetailsAsync(...) on a null object reference`

pointing to `RNIapModule.java` line 223. This implies that `mBillingClient` is unexpectedly `null` here. 

The variable `clientReady` is being used to track if the billing client setup has been completed, by setting it to `false` in the `onBillingServiceDisconnected()` callback. But `mBillingClient` itself is set to null immediately when `endConnection()` is called. This is a mismatch. It's possible for `clientReady` to remain set to `true`, even if `mBillingClient` is null. I believe this is what is happening, at least for my error. It seems that something is preventing `onBillingServiceDisconnected()` from being called.

I can confirm that I'm not getting `"billing client disconnected"` in logcat on unmount as expected, so `onBillingServiceDisconnected()` is indeed not being called.

To reproduce: mount a react-native component that calls `RNIap.getProducts()` on `componentDidMount` and `RNIap.endConnection()` on `componentWillUnmount`. Unmount the component and mount it again. The above error should occur.

Potential Fix: set `clientReady = false` within the `endConnection()` method (e.g. after line 179). I've tested this on device and it seems to work. Along with the existing changes discussed above, re-mounted the in-app purchase component multiple times doesn't seem to result in any errors or crashes. Also think about if it's necessary to set `mBillingClient` to null? I don't have any experience here so I can't say, but it does seem a little odd. I also don't see any other projects on Github nulling out the billing client in this callback.

**Comment by hyochan** [comment] 2019-01-07 01:44
@mitchellmcm27 Thanks for your catch. This is very promising and I agree with you. It was hard for me to fix the problem without any minimal reproduction. Also, I'd like to solve the problems together.

Please give us any `PR` if you have any thought of enhancing this problem.

Best, regards.

**Comment by mitchellmcm27** [comment] 2019-01-08 17:33
I've released 2.4.0-beta6 in the latest version of my app, with a few thousand upgrades so far. No crashes yet 👍

**Comment by Ilario17** [comment] 2019-01-09 10:04
I already have some crash with the same stacktrace but much less than before.

**Comment by levpopov** [comment] 2019-01-10 22:51
Also still getting same stacktrace on 2.4.0-beta6

**Comment by Ilario17** [comment] 2019-01-11 09:52
I think this bug report should be reopened.

![schermata 2019-01-11 alle 10 51 20](https://user-images.githubusercontent.com/33326791/51026461-daafbb80-158e-11e9-8949-7b24f599f83d.png)

In less than 24 hours.

**Comment by LinusU** [comment] 2019-01-11 13:57
I'm not sure that the recent changes didn't cause their own problems, e.g. if `mBillingClient` isn't null, but it isn't yet ready, the `ensureConnection` function will simply overwrite `mBillingClient` with a new client, throwing away the old one 🤔

**Comment by wasedaigo** [comment] 2019-01-13 03:52
I would like to know which version started showing this error, so that I can roll back to a stable version.

**Comment by mitchellmcm27** [comment] 2019-01-13 23:40
I too think the issue should be reopened. The original issue had to do with the callback, and the fixes for that surfaced the "null object reference" error. Although the latter may have been fixed (I agree with @LinusU that there may be more problems there), we are still dealing with the original issue.

I've gotten a few crashes related to the callback in beta6 as well.

**Comment by hyochan** [comment] 2019-01-15 06:51
I've reopened this. Hope someone can give `PR` for this.

**Comment by edo1493** [comment] 2019-01-21 10:17
Do you guys know when this was introduced? I'd be more than happy to roll back.

**Comment by dajaffe** [comment] 2019-01-23 16:29
I can confirm the crashes exist on beta6 as well as 2.3.23 on Android. Fairly easy to recreate per this [1] comment.

[1]
https://github.com/googlesamples/android-play-billing/issues/45#issuecomment-324466519

**Comment by hyochan** [comment] 2019-01-25 10:03
I've merged #379 and released to `beta8`. Please try that.

**Closed** 2019-02-12 04:39 UTC
Labels: android, bug, critical

**Comment by marioot** [comment] 2019-04-23 12:12
Is this fixed in the latest  version? Is it safe to upgrade to latest?

**Comment by fokoz** [comment] 2019-06-12 08:26
@hyochan this issue still appears in 3.0.0-rc-2 any idea?

**Comment by hyochan** [comment] 2019-06-12 15:57
Could you try `3.0.0-rc-4`? It will work perfectly (hopefully).

**Comment by fokoz** [comment] 2019-06-13 11:35
@hyochan If I use `try catch `this runtime error won't occur, I think rc-4 should resolve this.
 Thank you !
